{{- range .Values.repositories }}
---
apiVersion: v1
kind: Secret
metadata:
  name: repo-{{ . | adler32sum }}
  labels:
    argocd.argoproj.io/secret-type: repository
data:
  url: {{ . | b64enc }}
  type: {{ b64enc "git" }} 
  username: {{ b64enc "test.com" }}
  password: {{ b64enc "test" }}
{{- end }}